language: node_js
sudo: true
node_js:
- 9
cache:
  directories:
  - node_modules
script:
- npm install
- mocha app/client/spec/PostServiceClient.spec.js
- sleep 5
- node app/service/spec/PostService.spec.js
